# Generated by Django 4.1.3 on 2023-01-20 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_profile"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Group",
        ),
        migrations.DeleteModel(
            name="Profile",
        ),
    ]
